# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dal.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import DalMessageProperties_pb2 as DalMessageProperties__pb2
import DalPrivacyProperties_pb2 as DalPrivacyProperties__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='dal.proto',
  package='com.ditas.ehealth',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\tdal.proto\x12\x11\x63om.ditas.ehealth\x1a\x1a\x44\x61lMessageProperties.proto\x1a\x1a\x44\x61lPrivacyProperties.proto\"\xbc\x02\n\x18StartDataMovementRequest\x12\x45\n\x14\x64\x61lMessageProperties\x18\x01 \x01(\x0b\x32\'.com.ditas.ehealth.DalMessageProperties\x12H\n\x17sourcePrivacyProperties\x18\x02 \x01(\x0b\x32\'.com.ditas.ehealth.DalPrivacyProperties\x12M\n\x1c\x64\x65stinationPrivacyProperties\x18\x03 \x01(\x0b\x32\'.com.ditas.ehealth.DalPrivacyProperties\x12\r\n\x05query\x18\x04 \x01(\t\x12\x17\n\x0fqueryParameters\x18\x05 \x03(\t\x12\x18\n\x10sharedVolumePath\x18\x06 \x01(\t\"\x18\n\x16StartDataMovementReply\"\xd7\x02\n\x19\x46inishDataMovementRequest\x12\x45\n\x14\x64\x61lMessageProperties\x18\x01 \x01(\x0b\x32\'.com.ditas.ehealth.DalMessageProperties\x12H\n\x17sourcePrivacyProperties\x18\x02 \x01(\x0b\x32\'.com.ditas.ehealth.DalPrivacyProperties\x12M\n\x1c\x64\x65stinationPrivacyProperties\x18\x03 \x01(\x0b\x32\'.com.ditas.ehealth.DalPrivacyProperties\x12\r\n\x05query\x18\x04 \x01(\t\x12\x17\n\x0fqueryParameters\x18\x05 \x03(\t\x12\x18\n\x10sharedVolumePath\x18\x06 \x01(\t\x12\x18\n\x10targetDatasource\x18\x07 \x01(\t\"\x19\n\x17\x46inishDataMovementReply2\xf6\x01\n\x13\x44\x61taMovementService\x12m\n\x11startDataMovement\x12+.com.ditas.ehealth.StartDataMovementRequest\x1a).com.ditas.ehealth.StartDataMovementReply\"\x00\x12p\n\x12\x66inishDataMovement\x12,.com.ditas.ehealth.FinishDataMovementRequest\x1a*.com.ditas.ehealth.FinishDataMovementReply\"\x00\x62\x06proto3')
  ,
  dependencies=[DalMessageProperties__pb2.DESCRIPTOR,DalPrivacyProperties__pb2.DESCRIPTOR,])




_STARTDATAMOVEMENTREQUEST = _descriptor.Descriptor(
  name='StartDataMovementRequest',
  full_name='com.ditas.ehealth.StartDataMovementRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dalMessageProperties', full_name='com.ditas.ehealth.StartDataMovementRequest.dalMessageProperties', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sourcePrivacyProperties', full_name='com.ditas.ehealth.StartDataMovementRequest.sourcePrivacyProperties', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='destinationPrivacyProperties', full_name='com.ditas.ehealth.StartDataMovementRequest.destinationPrivacyProperties', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='query', full_name='com.ditas.ehealth.StartDataMovementRequest.query', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='queryParameters', full_name='com.ditas.ehealth.StartDataMovementRequest.queryParameters', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sharedVolumePath', full_name='com.ditas.ehealth.StartDataMovementRequest.sharedVolumePath', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=405,
)


_STARTDATAMOVEMENTREPLY = _descriptor.Descriptor(
  name='StartDataMovementReply',
  full_name='com.ditas.ehealth.StartDataMovementReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=407,
  serialized_end=431,
)


_FINISHDATAMOVEMENTREQUEST = _descriptor.Descriptor(
  name='FinishDataMovementRequest',
  full_name='com.ditas.ehealth.FinishDataMovementRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dalMessageProperties', full_name='com.ditas.ehealth.FinishDataMovementRequest.dalMessageProperties', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sourcePrivacyProperties', full_name='com.ditas.ehealth.FinishDataMovementRequest.sourcePrivacyProperties', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='destinationPrivacyProperties', full_name='com.ditas.ehealth.FinishDataMovementRequest.destinationPrivacyProperties', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='query', full_name='com.ditas.ehealth.FinishDataMovementRequest.query', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='queryParameters', full_name='com.ditas.ehealth.FinishDataMovementRequest.queryParameters', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sharedVolumePath', full_name='com.ditas.ehealth.FinishDataMovementRequest.sharedVolumePath', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='targetDatasource', full_name='com.ditas.ehealth.FinishDataMovementRequest.targetDatasource', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=434,
  serialized_end=777,
)


_FINISHDATAMOVEMENTREPLY = _descriptor.Descriptor(
  name='FinishDataMovementReply',
  full_name='com.ditas.ehealth.FinishDataMovementReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=779,
  serialized_end=804,
)

_STARTDATAMOVEMENTREQUEST.fields_by_name['dalMessageProperties'].message_type = DalMessageProperties__pb2._DALMESSAGEPROPERTIES
_STARTDATAMOVEMENTREQUEST.fields_by_name['sourcePrivacyProperties'].message_type = DalPrivacyProperties__pb2._DALPRIVACYPROPERTIES
_STARTDATAMOVEMENTREQUEST.fields_by_name['destinationPrivacyProperties'].message_type = DalPrivacyProperties__pb2._DALPRIVACYPROPERTIES
_FINISHDATAMOVEMENTREQUEST.fields_by_name['dalMessageProperties'].message_type = DalMessageProperties__pb2._DALMESSAGEPROPERTIES
_FINISHDATAMOVEMENTREQUEST.fields_by_name['sourcePrivacyProperties'].message_type = DalPrivacyProperties__pb2._DALPRIVACYPROPERTIES
_FINISHDATAMOVEMENTREQUEST.fields_by_name['destinationPrivacyProperties'].message_type = DalPrivacyProperties__pb2._DALPRIVACYPROPERTIES
DESCRIPTOR.message_types_by_name['StartDataMovementRequest'] = _STARTDATAMOVEMENTREQUEST
DESCRIPTOR.message_types_by_name['StartDataMovementReply'] = _STARTDATAMOVEMENTREPLY
DESCRIPTOR.message_types_by_name['FinishDataMovementRequest'] = _FINISHDATAMOVEMENTREQUEST
DESCRIPTOR.message_types_by_name['FinishDataMovementReply'] = _FINISHDATAMOVEMENTREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StartDataMovementRequest = _reflection.GeneratedProtocolMessageType('StartDataMovementRequest', (_message.Message,), {
  'DESCRIPTOR' : _STARTDATAMOVEMENTREQUEST,
  '__module__' : 'dal_pb2'
  # @@protoc_insertion_point(class_scope:com.ditas.ehealth.StartDataMovementRequest)
  })
_sym_db.RegisterMessage(StartDataMovementRequest)

StartDataMovementReply = _reflection.GeneratedProtocolMessageType('StartDataMovementReply', (_message.Message,), {
  'DESCRIPTOR' : _STARTDATAMOVEMENTREPLY,
  '__module__' : 'dal_pb2'
  # @@protoc_insertion_point(class_scope:com.ditas.ehealth.StartDataMovementReply)
  })
_sym_db.RegisterMessage(StartDataMovementReply)

FinishDataMovementRequest = _reflection.GeneratedProtocolMessageType('FinishDataMovementRequest', (_message.Message,), {
  'DESCRIPTOR' : _FINISHDATAMOVEMENTREQUEST,
  '__module__' : 'dal_pb2'
  # @@protoc_insertion_point(class_scope:com.ditas.ehealth.FinishDataMovementRequest)
  })
_sym_db.RegisterMessage(FinishDataMovementRequest)

FinishDataMovementReply = _reflection.GeneratedProtocolMessageType('FinishDataMovementReply', (_message.Message,), {
  'DESCRIPTOR' : _FINISHDATAMOVEMENTREPLY,
  '__module__' : 'dal_pb2'
  # @@protoc_insertion_point(class_scope:com.ditas.ehealth.FinishDataMovementReply)
  })
_sym_db.RegisterMessage(FinishDataMovementReply)



_DATAMOVEMENTSERVICE = _descriptor.ServiceDescriptor(
  name='DataMovementService',
  full_name='com.ditas.ehealth.DataMovementService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=807,
  serialized_end=1053,
  methods=[
  _descriptor.MethodDescriptor(
    name='startDataMovement',
    full_name='com.ditas.ehealth.DataMovementService.startDataMovement',
    index=0,
    containing_service=None,
    input_type=_STARTDATAMOVEMENTREQUEST,
    output_type=_STARTDATAMOVEMENTREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='finishDataMovement',
    full_name='com.ditas.ehealth.DataMovementService.finishDataMovement',
    index=1,
    containing_service=None,
    input_type=_FINISHDATAMOVEMENTREQUEST,
    output_type=_FINISHDATAMOVEMENTREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DATAMOVEMENTSERVICE)

DESCRIPTOR.services_by_name['DataMovementService'] = _DATAMOVEMENTSERVICE

# @@protoc_insertion_point(module_scope)
