# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class DatabaseInnerColumns(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, column_id: str=None):  # noqa: E501
        """DatabaseInnerColumns - a model defined in Swagger

        :param column_id: The column_id of this DatabaseInnerColumns.  # noqa: E501
        :type column_id: str
        """
        self.swagger_types = {
            'column_id': str
        }

        self.attribute_map = {
            'column_id': 'column_id'
        }
        self._column_id = column_id

    @classmethod
    def from_dict(cls, dikt) -> 'DatabaseInnerColumns':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The database_inner_columns of this DatabaseInnerColumns.  # noqa: E501
        :rtype: DatabaseInnerColumns
        """
        return util.deserialize_model(dikt, cls)

    @property
    def column_id(self) -> str:
        """Gets the column_id of this DatabaseInnerColumns.


        :return: The column_id of this DatabaseInnerColumns.
        :rtype: str
        """
        return self._column_id

    @column_id.setter
    def column_id(self, column_id: str):
        """Sets the column_id of this DatabaseInnerColumns.


        :param column_id: The column_id of this DatabaseInnerColumns.
        :type column_id: str
        """

        self._column_id = column_id
