# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.database import Database  # noqa: F401,E501
from swagger_server import util


class ReqBodyDataSources(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, data_source_id: str=None, data_source_type: str=None, database: Database=None):  # noqa: E501
        """ReqBodyDataSources - a model defined in Swagger

        :param data_source_id: The data_source_id of this ReqBodyDataSources.  # noqa: E501
        :type data_source_id: str
        :param data_source_type: The data_source_type of this ReqBodyDataSources.  # noqa: E501
        :type data_source_type: str
        :param database: The database of this ReqBodyDataSources.  # noqa: E501
        :type database: Database
        """
        self.swagger_types = {
            'data_source_id': str,
            'data_source_type': str,
            'database': Database
        }

        self.attribute_map = {
            'data_source_id': 'dataSource_id',
            'data_source_type': 'dataSource_type',
            'database': 'database'
        }
        self._data_source_id = data_source_id
        self._data_source_type = data_source_type
        self._database = database

    @classmethod
    def from_dict(cls, dikt) -> 'ReqBodyDataSources':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ReqBody_dataSources of this ReqBodyDataSources.  # noqa: E501
        :rtype: ReqBodyDataSources
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data_source_id(self) -> str:
        """Gets the data_source_id of this ReqBodyDataSources.


        :return: The data_source_id of this ReqBodyDataSources.
        :rtype: str
        """
        return self._data_source_id

    @data_source_id.setter
    def data_source_id(self, data_source_id: str):
        """Sets the data_source_id of this ReqBodyDataSources.


        :param data_source_id: The data_source_id of this ReqBodyDataSources.
        :type data_source_id: str
        """

        self._data_source_id = data_source_id

    @property
    def data_source_type(self) -> str:
        """Gets the data_source_type of this ReqBodyDataSources.


        :return: The data_source_type of this ReqBodyDataSources.
        :rtype: str
        """
        return self._data_source_type

    @data_source_type.setter
    def data_source_type(self, data_source_type: str):
        """Sets the data_source_type of this ReqBodyDataSources.


        :param data_source_type: The data_source_type of this ReqBodyDataSources.
        :type data_source_type: str
        """

        self._data_source_type = data_source_type

    @property
    def database(self) -> Database:
        """Gets the database of this ReqBodyDataSources.


        :return: The database of this ReqBodyDataSources.
        :rtype: Database
        """
        return self._database

    @database.setter
    def database(self, database: Database):
        """Sets the database of this ReqBodyDataSources.


        :param database: The database of this ReqBodyDataSources.
        :type database: Database
        """

        self._database = database
