# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.movements_enaction import MovementsEnaction  # noqa: F401,E501
from swagger_server.models.req_body_data_sources import ReqBodyDataSources  # noqa: F401,E501
from swagger_server import util


class ReqBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, data_sources: List[ReqBodyDataSources]=None, movements_enaction: MovementsEnaction=None):  # noqa: E501
        """ReqBody - a model defined in Swagger

        :param data_sources: The data_sources of this ReqBody.  # noqa: E501
        :type data_sources: List[ReqBodyDataSources]
        :param movements_enaction: The movements_enaction of this ReqBody.  # noqa: E501
        :type movements_enaction: MovementsEnaction
        """
        self.swagger_types = {
            'data_sources': List[ReqBodyDataSources],
            'movements_enaction': MovementsEnaction
        }

        self.attribute_map = {
            'data_sources': 'dataSources',
            'movements_enaction': 'movementsEnaction'
        }
        self._data_sources = data_sources
        self._movements_enaction = movements_enaction

    @classmethod
    def from_dict(cls, dikt) -> 'ReqBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ReqBody of this ReqBody.  # noqa: E501
        :rtype: ReqBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data_sources(self) -> List[ReqBodyDataSources]:
        """Gets the data_sources of this ReqBody.


        :return: The data_sources of this ReqBody.
        :rtype: List[ReqBodyDataSources]
        """
        return self._data_sources

    @data_sources.setter
    def data_sources(self, data_sources: List[ReqBodyDataSources]):
        """Sets the data_sources of this ReqBody.


        :param data_sources: The data_sources of this ReqBody.
        :type data_sources: List[ReqBodyDataSources]
        """

        self._data_sources = data_sources

    @property
    def movements_enaction(self) -> MovementsEnaction:
        """Gets the movements_enaction of this ReqBody.


        :return: The movements_enaction of this ReqBody.
        :rtype: MovementsEnaction
        """
        return self._movements_enaction

    @movements_enaction.setter
    def movements_enaction(self, movements_enaction: MovementsEnaction):
        """Sets the movements_enaction of this ReqBody.


        :param movements_enaction: The movements_enaction of this ReqBody.
        :type movements_enaction: MovementsEnaction
        """

        self._movements_enaction = movements_enaction
