# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class StartDM(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, target_path: str=None):  # noqa: E501
        """StartDM - a model defined in Swagger

        :param target_path: The target_path of this StartDM.  # noqa: E501
        :type target_path: str
        """
        self.swagger_types = {
            'target_path': str
        }

        self.attribute_map = {
            'target_path': 'target_path'
        }
        self._target_path = target_path

    @classmethod
    def from_dict(cls, dikt) -> 'StartDM':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The startDM of this StartDM.  # noqa: E501
        :rtype: StartDM
        """
        return util.deserialize_model(dikt, cls)

    @property
    def target_path(self) -> str:
        """Gets the target_path of this StartDM.


        :return: The target_path of this StartDM.
        :rtype: str
        """
        return self._target_path

    @target_path.setter
    def target_path(self, target_path: str):
        """Sets the target_path of this StartDM.


        :param target_path: The target_path of this StartDM.
        :type target_path: str
        """

        self._target_path = target_path
