# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DalMessageProperties.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DalMessageProperties.proto',
  package='com.ditas.ehealth',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1a\x44\x61lMessageProperties.proto\x12\x11\x63om.ditas.ehealth\"S\n\x14\x44\x61lMessageProperties\x12\x0f\n\x07purpose\x18\x01 \x01(\t\x12\x13\n\x0brequesterId\x18\x02 \x01(\t\x12\x15\n\rauthorization\x18\x03 \x01(\tb\x06proto3')
)




_DALMESSAGEPROPERTIES = _descriptor.Descriptor(
  name='DalMessageProperties',
  full_name='com.ditas.ehealth.DalMessageProperties',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='purpose', full_name='com.ditas.ehealth.DalMessageProperties.purpose', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='requesterId', full_name='com.ditas.ehealth.DalMessageProperties.requesterId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='authorization', full_name='com.ditas.ehealth.DalMessageProperties.authorization', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=132,
)

DESCRIPTOR.message_types_by_name['DalMessageProperties'] = _DALMESSAGEPROPERTIES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DalMessageProperties = _reflection.GeneratedProtocolMessageType('DalMessageProperties', (_message.Message,), {
  'DESCRIPTOR' : _DALMESSAGEPROPERTIES,
  '__module__' : 'DalMessageProperties_pb2'
  # @@protoc_insertion_point(class_scope:com.ditas.ehealth.DalMessageProperties)
  })
_sym_db.RegisterMessage(DalMessageProperties)


# @@protoc_insertion_point(module_scope)
